[package]
name = "game-sdl2-legion"
version = "0.1.0"
authors = ["Gregory McIntyre <greg@gregorymcintyre.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.2"
legion = "0.3.0"
gl = "0.14.0"
